/*
 * This file is generated by jOOQ.
 */
package exampleGenerati;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import classidb.Accountpersonale;
import classidb.Accountutenti;
import classidb.Piatti;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>AccountPersonale</code>.
     */
    public final Accountpersonale ACCOUNTPERSONALE = Accountpersonale.ACCOUNTPERSONALE;

    /**
     * The table <code>AccountUtenti</code>.
     */
    public final Accountutenti ACCOUNTUTENTI = Accountutenti.ACCOUNTUTENTI;

    /**
     * The table <code>Piatti</code>.
     */
    public final Piatti PIATTI = Piatti.PIATTI;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accountpersonale.ACCOUNTPERSONALE,
            Accountutenti.ACCOUNTUTENTI,
            Piatti.PIATTI
        );
    }
}
