/*
 * This file is generated by jOOQ.
 */
package exampleGenerati;


import classidb.Accountpersonale;
import classidb.Accountutenti;
import classidb.Piatti;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>AccountPersonale</code>.
     */
    public static final Accountpersonale ACCOUNTPERSONALE = Accountpersonale.ACCOUNTPERSONALE;

    /**
     * The table <code>AccountUtenti</code>.
     */
    public static final Accountutenti ACCOUNTUTENTI = Accountutenti.ACCOUNTUTENTI;

    /**
     * The table <code>Piatti</code>.
     */
    public static final Piatti PIATTI = Piatti.PIATTI;
}
